# Necessary information
main: za.co.wihan.blocksToCommands.blocksToCommands
name: BlocksToCommands
version: 3.12
author: ILoveAMac
depend: [Vault]
api-version: 1.13

# Registering commands
commands:
  btc:
    description: Main command for Blocks to commands plugin.